import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import RainbowProvider from "@/providers/RainbowProvider";
import Navbar from "@/components/navbar/Navbar";
import { Toaster } from "@/components/ui/sonner"
const poppins = Poppins({
  variable: "--font-poppins",

  weight:['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});



export const metadata: Metadata = {
  title: "HyperMint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} bg-neutral-700 antialiased`}
      >
        <RainbowProvider>
          <Navbar/>
          {children}
          <Toaster/>
        </RainbowProvider>
      </body>
    </html>
  );
}
